### ISSUE TITLE
Older Version in the CRAN Repository?

### ISSUE THREAD

**Issue by liberaliscomputing** [POLAR-fhiR/fhircrackr#127] opened 2022-09-29 20:57 UTC
Thanks to your effort in responding to our previous inquiry, we developed a Shiny app using `fhircrackr` which is an essential part of our development (See https://github.com/kids-first/clovoc-ui-data-dashboard)!

While deploying our Shiny app on our RStudio Connect instance, we ended up having this error:

```
09/29 20:45:31.587 (GMT)
Error in value[[3L]](cond) : unused argument (add_headers = cookies)
```

I figured, when installing directly from the CRAN repository, the available package is actually a previous version. In order to use the latest version on my local machine, I had to run `remotes::install_github(repo = "https://github.com/POLAR-fhiR/fhircrackr")`. Could you update the CRAN repository with the `master` branch so that we can install directly from CRAN?

**Comment by palmjulia** [comment] 2022-09-30 07:57
Hi! Yes, that is definetly because CRAN has an older version at the moment. The problem is that updating on CRAN is a bit of a hassle everytime so I'd like to make sure that all bug-fixes and improvements actually work as intended. Currently there is one issue where I'm still waiting on some feedback. I think it's going to be a at least a couple of weeks until I can upload to CRAN because there is a lot going on at the moment.

If the problem is just that you cannot install from GitHub to your RStudio Connect instance, than maybe you can transfer the source files manually to the server and install from source there? Let me know if that is an option and if you need help with that. I know this has be done with some servers of ours which aren't allowed a connection to the internet at all.

Anyway I'll close this issue as soon as the CRAN update is done.

**Comment by palmjulia** [comment] 2022-11-21 07:52
I finally managed to upload the new version (2.1.0) to CRAN, sorry it toook so long.

**Closed by palmjulia** 2022-11-21 07:52 UTC
Labels: enhancement
